#!/usr/bin/env/ python3

from flask_wtf import FlaskForm
from wtforms import RadioField, HiddenField, StringField, FieldList, PasswordField, BooleanField, SubmitField, IntegerField, SelectField, FormField
from wtforms.validators import DataRequired, Length, AnyOf, NumberRange
import pprint

class EdgeworkPrepForm(FlaskForm):
    plates = SelectField("Number of port plates:", choices=[0, 1, 2, 3, 4, 5])
    indicators = SelectField("Number of indicators:", choices=[0, 1, 2, 3, 4, 5])
    submit = SubmitField('Confirm')

class Portplate(FlaskForm):
    RJ = BooleanField("RJ-45")
    PS2 = BooleanField("PS/2")
    parallel = BooleanField("parallel")
    serial = BooleanField("serial")
    DVI = BooleanField("DVI")
    RCA = BooleanField("sterio RCA")

class testform(FlaskForm):
    string = StringField('teste')
    testfield = SelectField('TEST', choices=[(1, '1'), (2, '2'), (3, '3')], validate_choice=False)
    booltest = BooleanField('test')
    submit = SubmitField('test it')

class FullEdgeworkForm(FlaskForm):
    serial = StringField("Serial Number:", validators=[Length(min=6, max=6)])
    submit = SubmitField('Submit Edgework') 
    batteries = IntegerField("Battery count:")
    holders = IntegerField("Battery holder count:")
    Pcount = HiddenField('Pcount')
    Icount = HiddenField('Icount')

    PS21 = BooleanField("PS/2")
    RJ1 = BooleanField("RJ-45")
    DVI1 = BooleanField("DVI-D") 
    RCA1 = BooleanField("Sterio RCA") 
    parallel1 = BooleanField("Parallel") 
    serial1 = BooleanField("Serial")

    PS22 = BooleanField("PS/2")
    RJ2 = BooleanField("RJ-45")
    DVI2 = BooleanField("DVI-D") 
    RCA2 = BooleanField("Sterio RCA") 
    parallel2 = BooleanField("Parallel") 
    serial2 = BooleanField("Serial")

    PS23 = BooleanField("PS/2")
    RJ3 = BooleanField("RJ-45")
    DVI3 = BooleanField("DVI-D") 
    RCA3 = BooleanField("Sterio RCA") 
    parallel3 = BooleanField("Parallel") 
    serial3 = BooleanField("Serial")

    PS24 = BooleanField("PS/2")
    RJ4 = BooleanField("RJ-45")
    DVI4 = BooleanField("DVI-D") 
    RCA4 = BooleanField("Sterio RCA") 
    parallel4 = BooleanField("Parallel") 
    serial4 = BooleanField("Serial")

    PS25 = BooleanField("PS/2")
    RJ5 = BooleanField("RJ-45")
    DVI5 = BooleanField("DVI-D") 
    RCA5 = BooleanField("Sterio RCA") 
    parallel5 = BooleanField("Parallel") 
    serial5 = BooleanField("Serial")

    light1 = BooleanField("light on")
    label1 = SelectField("Label", choices=['BOB','CAR', 'CLR', 'FRK', 'FRQ', 'IND', 'MSA', 'NSA', 'SND', 'TRN'], validate_choice=False)

    light2 = BooleanField("light on")
    label2 = SelectField("Label", choices=['BOB','CAR', 'CLR', 'FRK', 'FRQ', 'IND', 'MSA', 'NSA', 'SND', 'TRN'], validate_choice=False)

    light3 = BooleanField("light on")
    label3 = SelectField("Label", choices=['BOB','CAR', 'CLR', 'FRK', 'FRQ', 'IND', 'MSA', 'NSA', 'SND', 'TRN'], validate_choice=False)

    light4 = BooleanField("light on")
    label4 = SelectField("Label", choices=['BOB','CAR', 'CLR', 'FRK', 'FRQ', 'IND', 'MSA', 'NSA', 'SND', 'TRN'], validate_choice=False)

    light5 = BooleanField("light on")
    label5 = SelectField("Label", choices=['BOB','CAR', 'CLR', 'FRK', 'FRQ', 'IND', 'MSA', 'NSA', 'SND', 'TRN'], validate_choice=False)

class wiresform(FlaskForm):
    wire1 = SelectField("Wire1", choices=['None','Black', 'White', 'Blue', 'Yellow', 'Red'], validate_choice=False)
    wire2 = SelectField("Wire2", choices=['None','Black', 'White', 'Blue', 'Yellow', 'Red'], validate_choice=False)
    wire3 = SelectField("Wire3", choices=['None','Black', 'White', 'Blue', 'Yellow', 'Red'], validate_choice=False)
    wire4 = SelectField("Wire4", choices=['None','Black', 'White', 'Blue', 'Yellow', 'Red'], validate_choice=False)
    wire5 = SelectField("Wire5", choices=['None','Black', 'White', 'Blue', 'Yellow', 'Red'], validate_choice=False)
    wire6 = SelectField("Wire6", choices=['None','Black', 'White', 'Blue', 'Yellow', 'Red'], validate_choice=False)
    submit = SubmitField("Process")    

class wiresequenceform(FlaskForm):
    color = RadioField("Color", choices=['Red', 'Black', 'Blue'])
    letter = RadioField("Letter", choices=['A', 'B', 'C'])
    submit = SubmitField('Check')
    hiddenred = HiddenField('red', default=0)
    hiddenblue = HiddenField('blue', default=0)
    hiddenblack = HiddenField('black', default=0)

class buttonform(FlaskForm):
    color = SelectField('Button Color', choices=['Other', 'Blue', 'White', 'Red', 'Yellow'], validate_choice=False) 
    label = SelectField('Button Label', choices=['Other', 'Abort', 'Detonate', 'Hold'], validate_choice=False)
    hold = HiddenField('hold?', default='False')
    light = SelectField('Light Color', choices=['Other', 'Yellow', 'Blue'], validate_choice=False)
    submit = SubmitField('PRESS!')

class keypadform(FlaskForm):
    symbol1 = RadioField('Symbol 1', choices=[u"ϙ", u"Ω", u"Ψ", u"Ϟ", u"Ж", u"Ѭ", u"Ѧ", u"Ԇ", u"¿", u"©", u"Ѯ", u"Ѣ", u"Ҋ", u"б", u"★", u"☆", u"ټ", u"Ѽ", u"ϗ", u"æ", u"Ӭ", u"¶", u"Ͼ", u"Ͽ", u"Ҩ", u"ƛ", u"҂"], validate_choice=False)
    symbol2 = RadioField('Symbol 2', choices=[ u"ϙ", u"Ω", u"Ψ", u"Ϟ", u"Ж", u"Ѭ", u"Ѧ", u"Ԇ", u"¿", u"©", u"Ѯ", u"Ѣ", u"Ҋ", u"б", u"★", u"☆", u"ټ", u"Ѽ", u"ϗ", u"æ", u"Ӭ", u"¶", u"Ͼ", u"Ͽ", u"Ҩ", u"ƛ", u"҂"], validate_choice=False)
    symbol3 = RadioField('Symbol 3', choices=[u"ϙ", u"Ω", u"Ψ", u"Ϟ", u"Ж", u"Ѭ", u"Ѧ", u"Ԇ", u"¿", u"©", u"Ѯ", u"Ѣ", u"Ҋ", u"б", u"★", u"☆", u"ټ", u"Ѽ", u"ϗ", u"æ", u"Ӭ", u"¶", u"Ͼ", u"Ͽ", u"Ҩ", u"ƛ", u"҂"], validate_choice=False)
    symbol4 = RadioField('Symbol 4', choices=[u"ϙ", u"Ω", u"Ψ", u"Ϟ", u"Ж", u"Ѭ", u"Ѧ", u"Ԇ", u"¿", u"©", u"Ѯ", u"Ѣ", u"Ҋ", u"б", u"★", u"☆", u"ټ", u"Ѽ", u"ϗ", u"æ", u"Ӭ", u"¶", u"Ͼ", u"Ͽ", u"Ҩ", u"ƛ", u"҂"], validate_choice=False)
    submit = SubmitField('Solve')

class needyknobform(FlaskForm):
    light11 = BooleanField('l11')
    light12 = BooleanField('l12')
    light13 = BooleanField('l13')
    light21 = BooleanField('l21')
    light22 = BooleanField('l22')
    light23 = BooleanField('l23')
    submit = SubmitField('Check')

class morseform(FlaskForm):
    text = StringField('Input word using text OR morse using "." for dot and "-" for dash', validators=[DataRequired()])
    submit = SubmitField('Submit')

class simonform(FlaskForm):
    flash = SelectField('Color Flashed', choices=['Red', 'Blue', 'Yellow', 'Green'], validate_choice=False)
    sequence = HiddenField('Sequence', default="")
    submit = SubmitField('Confirm')

class passwordform(FlaskForm):
    wheel = StringField('Letters in Wheel ', validators=[Length(min=6, max=6, message="Fill in all characters in the wheel")])
    oldwheels = HiddenField('old', default='')
    wheelnumber = HiddenField('count', default=1)
    submit = SubmitField('submit')

class WOFform(FlaskForm):
    display = StringField("What's on the display")
    position = StringField("What's in the given position")
    step = HiddenField('step', default='0')
    submit = SubmitField('Submit')

class memoryform(FlaskForm):
    stage = HiddenField('stage', default = '1')
    display = IntegerField('Number Displayed')
    missingtype = HiddenField('missing data', default='')
    missingpos = IntegerField('What position did they press')
    missingvalue = IntegerField('What was the label did they press')
    previousrounds = HiddenField('previous rounds', default='')
    holder = HiddenField('hold', default='')
    submit = SubmitField('Submit')   

class mazesform(FlaskForm):
    circle11 = BooleanField('1,1')
    circle21 = BooleanField('2,1')
    circle31 = BooleanField('3,1')
    circle41 = BooleanField('4,1')
    circle51 = BooleanField('5,1')
    circle61 = BooleanField('6,1')
    circle12 = BooleanField('1,2')
    circle22 = BooleanField('2,2')
    circle32 = BooleanField('3,2')
    circle42 = BooleanField('4,2')
    circle52 = BooleanField('5,2')
    circle62 = BooleanField('6,2')
    circle13 = BooleanField('1,3')
    circle23 = BooleanField('2,3')
    circle33 = BooleanField('3,3')
    circle43 = BooleanField('4,3')
    circle53 = BooleanField('5,3')
    circle63 = BooleanField('6,3')
    circle14 = BooleanField('1,4')
    circle24 = BooleanField('2,4')
    circle34 = BooleanField('3,4')
    circle44 = BooleanField('4,4')
    circle54 = BooleanField('5,4')
    circle64 = BooleanField('6,4')
    circle15 = BooleanField('1,5')
    circle25 = BooleanField('2,5')
    circle35 = BooleanField('3,5')
    circle45 = BooleanField('4,5')
    circle55 = BooleanField('5,5')
    circle65 = BooleanField('6,5')
    circle16 = BooleanField('1,6')
    circle26 = BooleanField('2,6')
    circle36 = BooleanField('3,6')
    circle46 = BooleanField('4,6')
    circle56 = BooleanField('5,6')
    circle66 = BooleanField('6,6')

    start11 = BooleanField('1,1')
    start21 = BooleanField('2,1')
    start31 = BooleanField('3,1')
    start41 = BooleanField('4,1')
    start51 = BooleanField('5,1')
    start61 = BooleanField('6,1')
    start12 = BooleanField('1,2')
    start22 = BooleanField('2,2')
    start32 = BooleanField('3,2')
    start42 = BooleanField('4,2')
    start52 = BooleanField('5,2')
    start62 = BooleanField('6,2')
    start13 = BooleanField('1,3')
    start23 = BooleanField('2,3')
    start33 = BooleanField('3,3')
    start43 = BooleanField('4,3')
    start53 = BooleanField('5,3')
    start63 = BooleanField('6,3')
    start14 = BooleanField('1,4')
    start24 = BooleanField('2,4')
    start34 = BooleanField('3,4')
    start44 = BooleanField('4,4')
    start54 = BooleanField('5,4')
    start64 = BooleanField('6,4')
    start15 = BooleanField('1,5')
    start25 = BooleanField('2,5')
    start35 = BooleanField('3,5')
    start45 = BooleanField('4,5')
    start55 = BooleanField('5,5')
    start65 = BooleanField('6,5')
    start16 = BooleanField('1,6')
    start26 = BooleanField('2,6')
    start36 = BooleanField('3,6')
    start46 = BooleanField('4,6')
    start56 = BooleanField('5,6')
    start66 = BooleanField('6,6')

    end11 = BooleanField('1,1')
    end21 = BooleanField('2,1')
    end31 = BooleanField('3,1')
    end41 = BooleanField('4,1')
    end51 = BooleanField('5,1')
    end61 = BooleanField('6,1')
    end12 = BooleanField('1,2')
    end22 = BooleanField('2,2')
    end32 = BooleanField('3,2')
    end42 = BooleanField('4,2')
    end52 = BooleanField('5,2')
    end62 = BooleanField('6,2')
    end13 = BooleanField('1,3')
    end23 = BooleanField('2,3')
    end33 = BooleanField('3,3')
    end43 = BooleanField('4,3')
    end53 = BooleanField('5,3')
    end63 = BooleanField('6,3')
    end14 = BooleanField('1,4')
    end24 = BooleanField('2,4')
    end34 = BooleanField('3,4')
    end44 = BooleanField('4,4')
    end54 = BooleanField('5,4')
    end64 = BooleanField('6,4')
    end15 = BooleanField('1,5')
    end25 = BooleanField('2,5')
    end35 = BooleanField('3,5')
    end45 = BooleanField('4,5')
    end55 = BooleanField('5,5')
    end65 = BooleanField('6,5')
    end16 = BooleanField('1,6')
    end26 = BooleanField('2,6')
    end36 = BooleanField('3,6')
    end46 = BooleanField('4,6')
    end56 = BooleanField('5,6')
    end66 = BooleanField('6,6')

    submit = SubmitField('Submit')
